"""Pure metadata helpers for solver output files."""


def build_solver_constants(
    *,
    Nx,
    Ny,
    Nz,
    Lx,
    Ly,
    Lz,
    hx,
    hy,
    hz,
    dt,
    T_final,
    omega,
    Vxy0,
    V0z,
    alpha,
    k_bc,
    theta,
    phi,
    z0,
    sigma_z,
    k0,
):
    """Build the constants dictionary saved by the spinor ABC solver."""
    return {
        "Nx": int(Nx),
        "Ny": int(Ny),
        "Nz": int(Nz),
        "Lx": float(Lx),
        "Ly": float(Ly),
        "Lz": float(Lz),
        "hx": float(hx),
        "hy": float(hy),
        "hz": float(hz),
        "dt": float(dt),
        "T_final": float(T_final),
        "omega": float(omega),
        "Vxy0": float(Vxy0),
        "V0z": float(V0z),
        "alpha": float(alpha),
        "k_bc": float(k_bc),
        "theta": float(theta),
        "phi": float(phi),
        "DTYPE_R": "float32",
        "DTYPE_C": "complex64",
        "z0": float(z0),
        "sigma_z": float(sigma_z),
        "k0": float(k0),
    }
